### ISSUE TITLE
Corrupted JSON file

### ISSUE THREAD

**Issue by mojtaba-komeili** [JerichoWorld/JerichoWorld#2] opened 2021-08-16 18:41 UTC
I used something like this to open the `train.json` file inside the zipped data file:
```python
import json

with open('/path/to/my/train.json`, 'r') as fi:
    data = json.load(fi)
```

But it crashes with the following error.

```
JSONDecodeError: Unterminated string starting at: line 1 column 388874138 (char 388874137)
```

**Comment by JerichoWorld** [comment] 2021-08-16 18:52
I'm not able to reproduce this unfortunately. I can open both train and test jsons with the json package in python and with a text editor like vim. Maybe its something to do with line ends and adding in a new line at the end of it will fix it?

**Comment by mojtaba-komeili** [comment] 2021-08-16 19:30
What OS and version of python are you using? I used Ubuntu and Mac with python 3.8.*. I am unable to run the above simple code, or use `loads` using its string, or use jsonlines to read the unzipped file. The zipped file seems to be corrupted. Here is the last 150 characters:
```
'm again?\' to himself.": ["statue", "hideous"], "He is a tall and slender young man. The most striking thing about him is his clothes, which looks at l'
```

**Comment by JerichoWorld** [comment] 2021-08-16 20:17
It looks like it was due to line end issues as I was using a Windows 10 machine. Data should be fixed to work with an Ubuntu machine as of the latest commit.

**Comment by mojtaba-komeili** [comment] 2021-08-16 20:22
Yes, thank you. I just checked the data and it loaded without any issues. Thanks again for quick response!

**Closed as completed** 2021-08-16 21:46 UTC
